Part 8 integration specs and fix n+1
henokkhm/microverse-rails-blog pull request #8
Opened 2023-11-09 19:08 UTC by henokkhm

This pull request addresses two main issues:
   1. fix the *N+1 problem* when fetching all posts and comments of a user
   2. use **Capybara** to write integration tests for each view 

The screenshots of the app's logs before and after implementing the fix for the *N+1 problem* are shown below.

### Before
![blog-app-n+1-before](https://github.com/henokkhm/microverse-rails-blog/assets/110997325/1d645b8f-84f6-4b85-bc47-d6685fe9b1e7)

### After
![blog-app-n+1-after](https://github.com/henokkhm/microverse-rails-blog/assets/110997325/962b2e8a-3827-4d92-992b-72e7e68f42d9)

## Summary
- Fix n+1 query for post comments
- Update database seeds script
- Use db seed for all tests
- Write test cases for each of the following views
  - posts index
  - post show
  - users index
  - user show
- **Remove outdated tests that check for placeholder text**

### All tests are passing
![Screenshot from 2023-11-09 21-35-26](https://github.com/henokkhm/microverse-rails-blog/assets/110997325/3a2c0bcf-17a1-4041-9bf2-7b2f3d39703b)

2023-11-09 19:26 UTC, fobadara requested changes
Hi team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![REDO](https://user-images.githubusercontent.com/62938735/260208741-25cd532c-dea0-4827-bb4f-5412e8493916.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 19:26 UTC, fobadara commented on spec/requests/integration/posts/post_index_spec.rb
[REQUIRED] Kindly include tests that asserts you can see a section for pagination if there are more posts than fit on the view.

2023-11-09 22:36 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ No linter errors 🟢 

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Your tests are failing as you can see below. Please try to make them pass 🙏 
![image](https://github.com/henokkhm/microverse-rails-blog/assets/46839548/911b70a1-0413-41be-be38-fa843626a622)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 22:55 UTC, henokkhm commented
Hi @codepantha, 

All the tests in the last commit are passing on my machine.
![image](https://github.com/henokkhm/microverse-rails-blog/assets/110997325/3995a637-48c6-441a-b2a2-fac4ade956fb)

Please make sure that you run `bin/rails db:environment:set RAILS_ENV=development` and then 'bin/rails db:reset' to populate your database with the records in **db/seeds.rb**

You can open the **/users** route to double-check that the data that the tests depend on was successfully added.

![image](https://github.com/henokkhm/microverse-rails-blog/assets/110997325/75570d39-7994-4436-ae26-5445ac04e063)

2023-11-10 05:24 UTC, Shedrack-Sunday approved these changes
Hi @henokkhm         👍 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails features  ✔️
- [x] Kudus on fixing all changes suggested by the last reviewer   
- [x] Kudus on meeting the requirements   👏 

### Confirmed view:
![image](https://github.com/henokkhm/microverse-rails-blog/assets/50990925/48cd0d3e-cd3f-4939-bb9f-c282510052a6)


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-10 07:09 UTC, merged